### ISSUE TITLE
Please close the stream.

### ISSUE THREAD

**Issue by cheonjeongdae** [STEMLab/InFactory#12]
I used Google Translator because I could not speak English.

If you are using try-with-resource or an existing version, try finally syntax
Please close the stream.

ex)
ByteArrayInputStream in = new ByteArrayInputStream(blob.getBytes(1, (int) blob.length()));
ObjectInputStream is = new ObjectInputStream(in);

good luck

**Comment by JungHam** [comment]
Hello, 
first of all, thank you for your advise on my project.
I fixed those part and committed at 'dev' branch. 
(Maybe some streams can be remained as opened. Soon I'll fix that parts.) 
As soon as possible I'll merge it with master.  
I'll keep the point in mind while using stream instances. 
Thanks!

천수석님 코드 리뷰 감사합니다ㅎㅎ 첫 리뷰어이자 기여자가 되어주셔서 감사해요. 좋은 하루 되세요!
