### ISSUE TITLE
package edu.pnu.stem.feature.core does not exist

### ISSUE THREAD

**Issue by rikwinters** [STEMLab/InFactory#20]
Hi, 

When I do mvn clean install, I get the following error that a package is missing:

/InFactory/igml-feature/src/main/java/edu/pnu/stem/binder/Mashaller.java:[17,32] error: package edu.pnu.stem.feature.core does not exist

**Comment by JungHam** [comment]
Hello, I checked that error. Please pull from master again.

**Comment by rikwinters** [comment]
Thank you, the issue is fixed!
