### ISSUE TITLE
How can i get source code of indoorgml-v_1_0-2.6.2-SNAPSHOT.jar

### ISSUE THREAD

**Issue by kunlinyu** [STEMLab/InFactory#44]
Hi every one!
I am wrapping InFactory as a map server for our application.
I notice that there are one jar file (indoorgml-v_1_0-2.6.2-SNAPSHOT.jar) in direcotry "lib". And some of java code (e.g. igml-feature/src/main/java/edu/pnu/stem/binder/Convert2FeatureClass.java) import this jar, and use the class inside it.
But I can not find the source code of indoorgml-v_1_0-2.6.2-SNAPSHOT.jar?

Do you have the source code ?
Maybe this jar was been generated from xsd using jaxb?

**Comment by kijouneli** [comment]
The jar file is made from the schema using JAXB.
You may find necessary binding files at https://github.com/highsource/ogc-schemas/tree/master/indoorgml/1.0/src/main/resources 
I hope it would be helpful.

**Comment by kunlinyu** [comment]
@kijouneli
Thanks! It helps a lot.
